# Default configuration for generate_descriptions.py
output_dir: "prompts"  # Directory where prompt files will be saved
log_level: "INFO"      # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
batch_size: 100        # Number of events to process in one batch
max_retries: 3         # Maximum number of retries for failed operations
timeout: 10            # Timeout in seconds for user input confirmations 